GET https://be-722144796089.us-central1.run.app/users

###
GET https://be-722144796089.us-central1.run.app/users/1

###
POST https://be-722144796089.us-central1.run.app/users
Content-Type: application/json

{
    "tag": "Re:Re: Help Me",
    "title": "Suggest",
    "content": "Ditt akuu takuut"
}

###
PATCH https://be-722144796089.us-central1.run.app/users/10
Content-Type: application/json

{
    "tag": "Re:Re: Help Me",
    "title": "Help",
    "content": "Ditt tolongin ditt"
}

###
DELETE https://be-722144796089.us-central1.run.app/users/10

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "huan", 
    "email": "huan@hu",
    "gender": "undifend", 
    "password": "help"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "huan@hu",
    "password": "help"
}

###
GET http://localhost:5000/note
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Imh1YW4iLCJlbWFpbCI6Imh1YW5AaHUiLCJnZW5kZXIiOiJ1bmRpZmVuZCIsImNyZWF0ZWRBdCI6IjIwMjUtMDUtMTRUMDQ6MzA6MjguMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjUtMDUtMThUMTI6NTM6MzAuMDAwWiIsImlhdCI6MTc0NzU3MjgxNywiZXhwIjoxNzQ3NTcyODQ3fQ.p5h2vKf73LJXcr3pKpxGuinmFt3XwZPAIpNaQwf7h3c

###
DELETE http://localhost:5000/users
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Imh1YW4iLCJlbWFpbCI6Imh1YW5AaHUiLCJnZW5kZXIiOiJ1bmRpZmVuZCIsImNyZWF0ZWRBdCI6IjIwMjUtMDUtMTRUMDQ6MzA6MjguMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjUtMDUtMThUMTI6NTM6MzcuMDAwWiIsImlhdCI6MTc0NzU3Mjg4OCwiZXhwIjoxNzQ3NjU5Mjg4fQ.FxaviBUY0zFXprGC4Y3lBnph0RIiQmq7gDIpH9y9kXg
